# Generated by Django 4.0.4 on 2022-06-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_quiz', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(verbose_name='문제번호')),
                ('content', models.CharField(max_length=250)),
                ('answer', models.IntegerField(verbose_name='문제해답')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(verbose_name='보기번호')),
                ('content', models.CharField(max_length=250)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_quiz.quizquestion')),
            ],
        ),
    ]
