# Generated by Django 4.0.4 on 2022-06-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_quiz", "0002_alter_quiz_options"),
        ("make_quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="answer",
        ),
        migrations.AddField(
            model_name="quizexample",
            name="answer",
            field=models.BooleanField(default=False, verbose_name="문제해답"),
        ),
        migrations.AlterField(
            model_name="quizexample",
            name="content",
            field=models.CharField(max_length=250, verbose_name="보기내용"),
        ),
        migrations.AlterField(
            model_name="quizexample",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="make_quiz.quizquestion",
                verbose_name="문제",
            ),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="content",
            field=models.CharField(max_length=250, verbose_name="문제내용"),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="my_quiz.quiz",
                verbose_name="퀴즈",
            ),
        ),
    ]
