# Generated by Django 4.0.4 on 2022-06-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
