# Generated by Django 4.0.4 on 2022-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizzes"},
        ),
        migrations.AddField(
            model_name="quiz",
            name="hit",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
