# Generated by Django 4.0.4 on 2022-06-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_quiz", "0003_quiz_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="public",
        ),
        migrations.AddField(
            model_name="quiz",
            name="private",
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
