# Generated by Django 4.0.4 on 2022-06-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_quiz", "0002_alter_quiz_options"),
        ("my_quiz", "0006_quiz_create_at_quiz_update_at"),
    ]

    operations = []
